### ISSUE TITLE
Tile KSampler Usage

### ISSUE THREAD

**Issue by paulo-coronado** [BlenderNeko/ComfyUI_TiledKSampler#1]
Hello, how is this node supposed to work? Is it with ControlNet Tile Model? Could you please provide an example?

Thank you so much and congratulations for the amazing work!

**Comment by BlenderNeko** [comment]
It functions the same way as the advanced sampler except for the 3 additional inputs specified in the readme, and the current lack of support of certain features. Now that most of the control nets are supported the tiled model should also work.
