### ISSUE TITLE
Installation Instructions?

### ISSUE THREAD

**Issue by tkocou** [BlenderNeko/ComfyUI_TiledKSampler#10]
So where does this content get installed in ComfyUI?

**Comment by BlenderNeko** [comment]
call `git clone https://github.com/BlenderNeko/ComfyUI_TiledKSampler.git` from the `custom_nodes` folder. Or take a look at [this](https://github.com/ltdrdata/ComfyUI-Manager) project.

**Comment by tkocou** [comment]
Thank you.
