### ISSUE TITLE
load_additional_models() missing 1 required positional argument: 'dtype'

### ISSUE THREAD

**Issue by KumaPlayWithShader** [BlenderNeko/ComfyUI_TiledKSampler#11]
I got error msg.
Error occurred when executing BNK_TiledKSamplerAdvanced:
load_additional_models() missing 1 required positional argument: 'dtype'

it's not work , since comfyUI being update....
not sure what's the problem.

**Comment by BlenderNeko** [comment]
try calling `git pull` from the tiled sampler folder
