### ISSUE TITLE
ModuleNotFoundError: No module named 'comfy.controlnet'

### ISSUE THREAD

**Issue by receptakill** [BlenderNeko/ComfyUI_TiledKSampler#20]
Hi; tried installing just now via the Manager and receive this issue when loading comfyui back up:

> Traceback (most recent call last):
>   File "C:\Users\X\Desktop\Comfy\ComfyUI\nodes.py", line 1665, in load_custom_node
>     module_spec.loader.exec_module(module)
>   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
>   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
>   File "C:\Users\X\Desktop\Comfy\ComfyUI\custom_nodes\ComfyUI_TiledKSampler\__init__.py", line 1, in <module>
>     from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
>   File "C:\Users\X\Desktop\Comfy\ComfyUI\custom_nodes\ComfyUI_TiledKSampler\nodes.py", line 12, in <module>
>     import comfy.controlnet
> ModuleNotFoundError: No module named 'comfy.controlnet'
> 
> Cannot import C:\Users\X\Desktop\Comfy\ComfyUI\custom_nodes\ComfyUI_TiledKSampler module for custom nodes: No module named 'comfy.controlnet'

Any idea what's missing here?  I checked other controlnet themed nodes via manager but didn't look like anything obvious that would resolve it.

**Comment by BlenderNeko** [comment]
update ComfyUI

**Comment by receptakill** [comment]
That was it!  I'm a dummy.  Thanks for humoring me.
