### ISSUE TITLE
Is the Tile ControlNet model supposed to work?

### ISSUE THREAD

**Issue by spasidom** [BlenderNeko/ComfyUI_TiledKSampler#35]
When applying the tile ControlNet model to the Tiled KSampler, it applies to each tile individually creating a grid of cloned images. Is this expected or could I fix this?

Example: 
![example](https://github.com/BlenderNeko/ComfyUI_TiledKSampler/assets/149066048/c70c060b-e868-4234-87bc-1f7ae574c3ed)

**Comment by yorkb** [comment]
I had this issue too but found it to be a caused by another custom node. I'm not sure exactly which it was as I disabled a bunch, but it could have been comfyroll.
