### ISSUE TITLE
Can't use 2M SDE sampler

### ISSUE THREAD

**Issue by Rkkss** [BlenderNeko/ComfyUI_TiledKSampler#9]
it create pixaled tiles at 4 corner. I've tried both normal/karras with padding/random tile method 
Edit: SDE++ also doesn't work

**Comment by BlenderNeko** [comment]
I can reproduce this for random, but not for padded. Are you using an NVIDEA card or something else?

**Comment by Rkkss** [comment]
Nvidia yes.  
I was sure I had tested with padded before. Now can't reproduce it, Weird. Mistake perhaps

**Comment by BlenderNeko** [comment]
I've reverted back the old random tiling behavior that is compatible with SDE, the new random tiling behavior can now be found under `random strict`
